version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    tty: true
    stdin_open: true

  db:
    image: mysql:8.0
    volumes:
      - './db/data:/var/lib/mysql'
      - './db/my.cnf:/etc/mysql/conf.d/my.cnf'
    env_file:
      - variables.env
    ports:
      - '3306:3306'
