services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true

  backend:
    build: ./backend
    ports:
      - '8000:8000'
    tty: true
    stdin_open: true
    env_file:
      - ./variables.env
    environment:
      - MYSQL_HOST=db
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: mysql:8.0
    volumes:
      - './db/data:/var/lib/mysql'
      - './db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './db/init.sql:/docker-entrypoint-initdb.d/init.sql'
    env_file:
      - ./variables.env
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
